# SVD step-by-step

In [1]:
import numpy as np


# Easy SVD
k = 2
A = np.array([
    [1, 2, 1],
    [3, 0, 1],
    [1, 1, 3],
    [8, 0, 12]
])

B = np.dot(A.T, A)

In [2]:
print B

[[ 75   3 103]
 [  3   5   5]
 [103   5 155]]


In [3]:
lb, vb = np.linalg.eig(B)

In [4]:
print lb

[ 225.64788601    4.28842295    5.06369103]


In [5]:
sigmas = np.array([np.sqrt(x) for x in lb])
r = np.array([np.dot(A, vb.T[i]) / s for i, s in enumerate(sigmas)])

In [6]:
# sort according to eigenvalues and get K
lpos = [i for i, w in sorted(enumerate(lb), key=lambda j: -j[1])][:k]
ssigmas = [sigmas[i] for i in lpos]
sr = np.array([r[i] for i in lpos])
svb = np.array([vb.T[i] for i in lpos])

Sigma = np.diag(ssigmas)
U = sr.T
V = svb

P1 = np.dot(U, Sigma)
P2 = np.dot(P1, V)


In [7]:
print Sigma
print U
print V
print P2

[[ 15.02158068   0.        ]
 [  0.           2.25026466]]
[[-0.0960134  -0.67869231]
 [-0.16766974  0.47458576]
 [-0.20409543 -0.55109303]
 [-0.9596944   0.10218404]]
[[-0.56456597 -0.02637021 -0.82496659]
 [ 0.44947791 -0.84811253 -0.28049018]]
[[  0.12779879   1.33330216   1.6182021 ]
 [  1.9019693   -0.8393186    1.77826639]
 [  1.17346677   1.13259546   2.87704956]
 [  8.24220809   0.18514032  11.82832683]]


In [8]:
print np.allclose(P2, A) # for K = A.shape[1]
print P2
print A

False
[[  0.12779879   1.33330216   1.6182021 ]
 [  1.9019693   -0.8393186    1.77826639]
 [  1.17346677   1.13259546   2.87704956]
 [  8.24220809   0.18514032  11.82832683]]
[[ 1  2  1]
 [ 3  0  1]
 [ 1  1  3]
 [ 8  0 12]]


In [9]:
# numpy version
Unp, snp, Vnp = np.linalg.svd(A, full_matrices=False)
Snp = np.diag(snp)
Pn2 = np.dot(np.dot(Unp, Snp), Vnp)

print np.allclose(Pn2, A)

print Pn2





True
[[  1.00000000e+00   2.00000000e+00   1.00000000e+00]
 [  3.00000000e+00  -1.66871435e-15   1.00000000e+00]
 [  1.00000000e+00   1.00000000e+00   3.00000000e+00]
 [  8.00000000e+00   1.05199601e-15   1.20000000e+01]]


full_matrices : bool, optional

If True (default), u and v have the shapes (M, M) and (N, N), respectively. Otherwise, the shapes are (M, K) and (K, N), respectively, where K = min(M, N).