# SVD step-by-step

In [1]:
import numpy as np
import pandas as pd
from tqdm.notebook import tqdm

In [2]:
A = np.array([
    [8, 2],
    [6, 4],
    [4, 6]
])

U = np.linalg.eig(A.dot(A.T))[1]
V = np.linalg.eig(A.T.dot(A))[1]

In [3]:
print(U.shape, V.shape)

(3, 3) (2, 2)


In [4]:
eigenvalues1 = np.linalg.eig(A.dot(A.T))[0]
eigenvalues2 = np.linalg.eig(A.T.dot(A))[0]

In [5]:
[x for x in np.round(eigenvalues1, 3) if x > 0]

[156.682, 15.318]

In [6]:
[x for x in np.round(eigenvalues2, 3) if x > 0]

[156.682, 15.318]

In [7]:
Sigma = np.zeros(A.shape)
Sigma[:A.shape[1], :A.shape[1]] = np.diag([np.sqrt(x) for x in [x for x in np.round(eigenvalues1, 3) if x > 0]])

In [8]:
Sigma

array([[12.51726807,  0.        ],
       [ 0.        ,  3.91382166],
       [ 0.        ,  0.        ]])

In [9]:
X = U.dot(Sigma).dot(V)

In [10]:
np.round(X, 3)

array([[-8.,  2.],
       [-6.,  4.],
       [-4.,  6.]])

# With SVD
Note the effect of vector normalization as produced by `np.linalg.eig`

In [11]:
Us, Ds, Vs = np.linalg.svd(A)
Sigmas = np.zeros(A.shape)
Sigmas[:A.shape[1], :A.shape[1]] = np.diag(Ds)

In [12]:
Us.dot(Sigmas).dot(Vs)

array([[8., 2.],
       [6., 4.],
       [4., 6.]])

# LSI

In [13]:
A = np.array([
    [1,2,3,4,5,6,7,8,9,10],
    [11,12,13,14,15,16,17,18,19,20],
    [21,22,23,24,25,26,27,28,29,30]])

In [14]:
U, s, VT = np.linalg.svd(A)

In [15]:
print(A.shape, U.shape, s.shape, VT.shape)

(3, 10) (3, 3) (3,) (10, 10)


In [16]:
Sigma = np.zeros((A.shape[0], A.shape[1]))
Sigma[:A.shape[0], :A.shape[0]] = np.diag(s)

In [17]:
k = 2

In [18]:
Sigma = Sigma[:k, :k]
U = U[:, :k]
VT = VT[:k, :]

In [19]:
print(A.shape, U.shape, Sigma.shape, VT.shape)

(3, 10) (3, 2) (2, 2) (2, 10)


In [20]:
U.dot(Sigma)

array([[-18.52157747,   6.47697214],
       [-49.81310011,   1.91182038],
       [-81.10462276,  -2.65333138]])

In [22]:
Sigma.dot(VT)

array([[-23.40685373, -24.94800949, -26.48916526, -28.03032102,
        -29.57147679, -31.11263255, -32.65378832, -34.19494409,
        -35.73609985, -37.27725562],
       [ -3.88834138,  -3.09787386,  -2.30740633,  -1.51693881,
         -0.72647129,   0.06399624,   0.85446376,   1.64493128,
          2.43539881,   3.22586633]])